#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config focus_follows_pointer false
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#42a5f5"
bspc config focused_border_color	"#42a5f5"
bspc config presel_feedback_color	"#42a5f5"
bspc config urgent_border_color 	"#dd2727"


#Find out names with arandr or xrandr
if xrandr -q | grep "DP2-1 con" ; then
    #Triple monitor when docked
    bspc monitor DP2-1 -d 2 3 4 5
    bspc monitor DP2-2 -d 6 7 8 9
    bspc monitor eDP1 -d 1
elif xrandr -q | grep "HDMI2 con" ; then
    #Dual monitor when presenting in meeting room
    bspc monitor HDMI2 -d 6 7 8 9
    bspc monitor eDP1 -d 1 2 3 4 5
elif xrandr -q | grep "DP2 con" ; then
    #Dual monitor when presenting in core
    bspc monitor DP2 -d 6 7 8 9
    bspc monitor eDP1 -d 1 2 3 4 5
else
    #Single monitor
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
#bspc rule -a Gimp state=fullscreen

# Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on

# Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Zathura state=tiled

# Open applications on specific workspaces
#bspc rule -a Firefox desktop='^1' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
#bspc rule -a Thunar desktop='^8' follow=on
#bspc rule -a discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^10' follow=on

#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

# Polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
